version: '3.7'
services:
  
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
    ports:
      - "5432:5432"
    networks:
      - opensearch-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.security.enabled: false
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    networks:
      - opensearch-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.6.2
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - opensearch-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.6.2
    ports:
      - 5000:5000
    depends_on:
      - elasticsearch
    networks:
      - opensearch-net
    volumes:
      - ./products.conf:/usr/share/logstash/pipeline/products.conf
      - ./postgresql-42.5.2.jar:/usr/share/logstash/vendor/jar/jdbc/postgresql-42.5.2.jar

volumes:
  esdata:
    driver: local

networks:
  opensearch-net: